2025-01-12 17:22:38,242 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Алексей\Documents\web\urban\module_12\tests_12_4.py", line 69, in test_run
    same = Runner({'name': 'Run'})
  File "C:\Users\Алексей\Documents\web\urban\module_12\tests_12_4.py", line 8, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано dict
2025-01-12 17:22:38,247 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Алексей\Documents\web\urban\module_12\tests_12_4.py", line 58, in test_walk
    same = Runner('Walk', -30)
  File "C:\Users\Алексей\Documents\web\urban\module_12\tests_12_4.py", line 13, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -30
